# Generated by Django 5.2.3 on 2025-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
