# Generated by Django 5.2.3 on 2025-06-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
