# Generated by Django 5.2.3 on 2025-06-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
