# Generated by Django 5.2.3 on 2025-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitimas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitima',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='vitima',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='vitima',
            name='situacao',
        ),
        migrations.AddField(
            model_name='vitima',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='vitima',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='vitima',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='vitima',
            name='numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='vitima',
            name='senha',
            field=models.CharField(default='senha123', max_length=128),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitima',
            name='telefone',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
