# Generated by Django 5.2.3 on 2025-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitimas', '0002_remove_vitima_endereco_remove_vitima_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitima',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
